-- sql is generated by devinggo
-- @Link  https://github.com/huagelong/devinggo
-- @Copyright  Copyright (c) 2024 devinggo
-- @Author  Kai <hpuwang@gmail.com>
-- @License  https://github.com/huagelong/devinggo/blob/master/LICENSE

/*Data for the table `system_modules` */

INSERT INTO `system_modules` (
  `created_at`, 
  `updated_at`, 
  `created_by`, 
  `updated_by`, 
  `name`, 
  `label`, 
  `description`, 
  `installed`, 
  `status`
) VALUES (
  NOW(), 
  NOW(), 
  1, 
  1, 
  'cms', 
  'Cms模块', 
  'Cms模块', 
  1, 
  1
);