// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalCmsTopicDao is internal type for wrapping internal DAO implements.
type internalCmsTopicDao = *internal.CmsTopicDao

// cmsTopicDao is the data access object for table cms_topic.
// You can define custom methods on it to extend its functionality as you wish.
type cmsTopicDao struct {
	internalCmsTopicDao
}

var (
	// CmsTopic is globally public accessible object for table cms_topic operations.
	CmsTopic = cmsTopicDao{
		internal.NewCmsTopicDao(),
	}
)

// Fill with you ideas below.
